### ISSUE TITLE
A is in NONPRIV

### ISSUE THREAD

**Issue by RobinMorisset** [KhronosGroup/Vulkan-MemoryModel#23]
The spec says: "Atomic operations are always considered non-private."
I did not see any translation of that sentence in the formal model, and it would be more convenient to have all such rules in one place. So I suggest adding
A in NONPRIV
just below NONPRIV in R+W

**Comment by jeffbolznv** [comment]
Some stuff like this is currently guaranteed by the litmus test generation code:

```
        // AV, VIS, and atomics are all implicitly nonpriv
        if (AV.find(instnum) != AV.end() ||
            VIS.find(instnum) != VIS.end() ||
            A.find(instnum) != A.end()) {
            NONPRIV.insert(instnum);
        }
```

and since .test.gen files have an explicit list of events that NONPRIV equals, it is effectively enforced there. But that only applies for the litmus tests, and not for the assertion tests, so there is a hole here.

In general, it is nice to distinguish between "requirements of a valid program" where the relation between certain things is fixed (e.g. A must be a subset of NONPRIV), vs things that alloy is allowed to explore when we don't provide a specific program as input. There are probably other cases of things that must be fixed that aren't reflected in the alloy model, and I agree we should add them to the model.
