### ISSUE TITLE
How to interpret data race expected results

### ISSUE THREAD

**Issue by hernanponcedeleon** [KhronosGroup/Vulkan-MemoryModel#30]
I am trying to understand how I should interpret the expected results related to data races in the litmus tests. Consider the example below.
```
NEWWG
NEWSG
NEWTHREAD
st.av.scopedev.sc0 x = 1
st.atom.rel.scopewg.sc1.semsc0 y = 1
NEWSG
NEWTHREAD
ld.atom.acq.scopewg.sc1.semsc0 y = 1
ld.vis.scopedev.sc0 x
SATISFIABLE consistent[X] && #dr=0
NOSOLUTION consistent[X] && #dr>0
```
Which of the following interpretations is correct?
- "the program does not contain **any** racy execution", or 
- "the execution in which the second thread observes `y=1` is not racy"

Put it differently, do the values enforced in the syntax always filter executions? This makes sense to enforce a safety/reachability condition, but I would expect that while reasoning about data races, one cares about all executions.

**Comment by jeffbolznv** [comment]
> Put it differently, do the values enforced in the syntax always filter executions? 

Yes, because `ld.atom.acq.scopewg.sc1.semsc0 y = 1` has the `= 1` on it, it limits the executions that are considered to only those where the load reads the value 1.

> SATISFIABLE consistent[X] && #dr=0

This one should be interpreted as "There exists a consistent execution with no data races."

> NOSOLUTION consistent[X] && #dr>0

This one should be interpreted as "There does not exist any consistent execution with a data race."

**Comment by hernanponcedeleon** [comment]
Thanks @jeffbolznv for the clarification
